In [1]:
import json 
import requests 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import pickle
import datetime as dt
from tqdm.notebook import tqdm
from IPython.display import Image

In [2]:
pd.set_option('max_columns', 100) # To see 50 columns
pd.set_option('max_rows', 100) # To see 100 rows

In [3]:
api = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJYLUFwcC1SYXRlLUxpbWl0IjoiNTAwOjEwIiwiYWNjb3VudF9pZCI6IjE1MTAyMjA3NzUiLCJhdXRoX2lkIjoiMiIsImV4cCI6MTY3NzQwMTAwNCwiaWF0IjoxNjYxODQ5MDA0LCJuYmYiOjE2NjE4NDkwMDQsInNlcnZpY2VfaWQiOiI0MzAwMTE0ODEiLCJ0b2tlbl90eXBlIjoiQWNjZXNzVG9rZW4ifQ.ngxIAncZ_jyxdeoYK12MPUkl_7SU7U7mEAyysZ7IC_k'

In [4]:
headers = {'Authorization': api}

In [ ]:
total=[]
for i in tqdm(range(68660,1000000)):
    match = requests.get(f'https://api.nexon.co.kr/fifaonline4/v1.0/matches?matchtype=50&offset={i*100}&limit=100&orderby=desc',headers=headers, timeout=5)
    match=match.json()
    match=pd.DataFrame(match)
    total.append(match)
        
result=pd.concat(total, ignore_index=True)

  0%|          | 0/931340 [00:00<?, ?it/s]

In [58]:
result=pd.concat(total, ignore_index=True)
result

                                0
0        630fbda703e986834d491e25
1        630fbd9b392b8e57e77a47e2
2        630fbc541c290ff528e79419
3        630fbc1bcdd434877a167fa4
4        630fbbf2a2425c725cc5c1b7
...                           ...
3398371  63090436f55d437ea6405362
3398372  63090436dd142b2cb816584a
3398373  63090436c79b5a2c28a59170
3398374  63090436b9104b1eddf006aa
3398375  630904369c7dc698f7b300b8

[3398376 rows x 1 columns]

In [153]:
match_url='https://api.nexon.co.kr/fifaonline4/v1.0/matches/{}'
match_urls=[]
for i in tqdm(result[0]): # total아니라 result[0]으로 하셔야해용
    
    match_urls.append(f'https://api.nexon.co.kr/fifaonline4/v1.0/matches/{i}'.format(i)) #여기서 total이 아니라 i 쓰셔야해요!

match_urls=pd.DataFrame(match_urls)
match_urls

  0%|          | 0/3398376 [00:00<?, ?it/s]

                                                         0
0        https://api.nexon.co.kr/fifaonline4/v1.0/match...
1        https://api.nexon.co.kr/fifaonline4/v1.0/match...
2        https://api.nexon.co.kr/fifaonline4/v1.0/match...
3        https://api.nexon.co.kr/fifaonline4/v1.0/match...
4        https://api.nexon.co.kr/fifaonline4/v1.0/match...
...                                                    ...
3398371  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398372  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398373  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398374  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398375  https://api.nexon.co.kr/fifaonline4/v1.0/match...

[3398376 rows x 1 columns]

In [121]:
df_yu = match_urls.loc[1699189:]
df_sh = match_urls.loc[:1699188]

In [122]:
df_yu.to_csv('match_urls_yu.csv')
df_sh.to_csv('match_urls_sh.csv')

In [155]:
match_urls.to_csv("match_urls.csv", index = False)

In [140]:
df_sh = pd.read_csv("match_urls_sh.csv")
df_sh

         Unnamed: 0                                                  0
0                 0  https://api.nexon.co.kr/fifaonline4/v1.0/match...
1                 1  https://api.nexon.co.kr/fifaonline4/v1.0/match...
2                 2  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3                 3  https://api.nexon.co.kr/fifaonline4/v1.0/match...
4                 4  https://api.nexon.co.kr/fifaonline4/v1.0/match...
...             ...                                                ...
1699184     1699184  https://api.nexon.co.kr/fifaonline4/v1.0/match...
1699185     1699185  https://api.nexon.co.kr/fifaonline4/v1.0/match...
1699186     1699186  https://api.nexon.co.kr/fifaonline4/v1.0/match...
1699187     1699187  https://api.nexon.co.kr/fifaonline4/v1.0/match...
1699188     1699188  https://api.nexon.co.kr/fifaonline4/v1.0/match...

[1699189 rows x 2 columns]

In [143]:
match_urls = df_sh.drop('Unnamed: 0', axis =1)

In [150]:
match_urls['0'][1]

'https://api.nexon.co.kr/fifaonline4/v1.0/matches/630fbd9b392b8e57e77a47e2'

In [149]:
match_urls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1699189 entries, 0 to 1699188
Data columns (total 1 columns):
 #   Column  Dtype
---  ------  -----
 0   0       object
dtypes: object(1)
memory usage: 13.0+ MB

In [145]:
r3 = []
i = 0

pbar = tqdm(desc='while loop',total = 1000000000)
while i <1000000000:
    j = match_urls[0][i]
    r= requests.get(j,headers=headers)
    r2=r.json()
    r3.append(r2)
    i += 1000
    pbar.update(i)
        
print('Loop completed')
pbar.close()

while loop:   0%|          | 0/1000000000 [00:00<?, ?it/s]

KeyError: 0

In [126]:
r3=pd.DataFrame(r3)
r3

,matchId,matchDate,matchType,matchInfo
0,630fbda703e986834d491e25,2022-09-01T04:59:47,50,"[{'accessId': '6f4b6c8ead903427e660c6b0', 'nic..."
1,630fb8e679b7959423e98e40,2022-09-01T04:48:58,50,"[{'accessId': '38f9d9719d2e134900b6f4cb', 'nic..."
2,630fb6740bdaf8038c62fccd,2022-09-01T04:39:04,50,"[{'accessId': 'f60ee941f099ded5b35a4efb', 'nic..."
3,630fb41f166e9ca9b76d26d4,2022-09-01T04:29:02,50,"[{'accessId': 'e68df0194e68d9959eb5cd4c', 'nic..."
4,630fb1ca371c605497c5fe72,2022-09-01T04:20:53,50,"[{'accessId': '3cece623159003c58a572eac', 'nic..."
5,630fafb6a55dfd4cac79d9f5,2022-09-01T04:11:17,50,"[{'accessId': 'd3af4c4d4074946b654a6d55', 'nic..."
6,630fada11ec3e5dab13ace60,2022-09-01T04:01:18,50,"[{'accessId': '8b14c2b9bffe3db1179d86db', 'nic..."
7,630fabdb985125928cabcaa8,2022-09-01T03:53:42,50,"[{'accessId': '40686625a46f07e8d4032783', 'nic..."
8,630faa1ce88dfba3f99f2289,2022-09-01T03:47:05,50,"[{'accessId': '25412cbd45f59eda4847f0e5', 'nic..."
9,630fa89308bf323d013a8224,2022-09-01T03:39:56,50,"[{'accessId': '2978ebf2e91fde24b3b9e4f4', 'nic..."
10,630fa72156127e774bb05241,2022-09-01T03:34:58,50,"[{'accessId': 'c7ebe0482998468be37abcd2', 'nic..."
11,630fa5b62cbc6751ba89f782,2022-09-01T03:27:57,50,"[{'accessId': '90b248eb1cd0ef4393004ed6', 'nic..."
12,630fa457b220c85dae2129ad,2022-09-01T03:21:25,50,"[{'accessId': '1d32872b6040282eee67a15f', 'nic..."

In [92]:
# 한번 내보내기
r3.to_csv("api_sample.csv",index = False)

In [128]:
print(i)

13000

In [129]:
# 자르고 계속
match_urls2 = match_urls.loc[14000:]
match_urls2

                                                         0
14000    https://api.nexon.co.kr/fifaonline4/v1.0/match...
14001    https://api.nexon.co.kr/fifaonline4/v1.0/match...
14002    https://api.nexon.co.kr/fifaonline4/v1.0/match...
14003    https://api.nexon.co.kr/fifaonline4/v1.0/match...
14004    https://api.nexon.co.kr/fifaonline4/v1.0/match...
...                                                    ...
3398371  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398372  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398373  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398374  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398375  https://api.nexon.co.kr/fifaonline4/v1.0/match...

[3384376 rows x 1 columns]

In [94]:
r3 = []
i = 0

pbar = tqdm(desc='while loop',total = 1000000000)
while i <1000000000:
    j = match_urls[0][i]
    r= requests.get(j,headers=headers)
    r2=r.json()
    r3.append(r2)
    i += 1000
    pbar.update(i)
        
print('Loop completed')
pbar.close()

  0%|          | 0/3365380 [00:00<?, ?it/s]

ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

In [95]:
r3=pd.DataFrame(r3)
r3

,matchId,matchDate,matchType,matchInfo
0,630f902bdaa4ab457d80d526,2022-09-01T02:01:54,50,"[{'accessId': '38f89da916b3455445b303e9', 'nic..."
1,630f8ffee3bc6523b853c125,2022-09-01T02:00:13,50,"[{'accessId': '8ddd8a2e773ba58810d85038', 'nic..."
2,630f8fe2ce134c543bb65992,2022-09-01T02:00:46,50,"[{'accessId': '1f125750eae226adf9ab3878', 'nic..."
3,630f8f6d7199900902a1d249,2022-09-01T02:01:00,50,"[{'accessId': 'cb542e3f735dfd3e5b9f3039', 'nic..."
4,630f851d00e8d130df4a7272,2022-09-01T00:59:31,50,"[{'accessId': 'f8f75e9fc25f7c2914f71115', 'nic..."
...,...,...,...,...
95417,630f6a41b464844a526ce6f6,2022-08-31T23:12:09,50,"[{'accessId': '8f5729ad8930a47b587ea4d2', 'nic..."
95418,630f6a41ae6dd7562cb5905a,2022-08-31T23:15:40,50,"[{'accessId': '3bcf8fb0dcb4b512f3e25756', 'nic..."
95419,630f6a41a0a6ec825a0101a3,2022-08-31T23:14:49,50,"[{'accessId': '36fe21c2f34cd7d73609ff88', 'nic..."
95420,630f6a4171d70963291886a0,2022-08-31T23:13:46,50,"[{'accessId': '19ab9de1bd4bd474574e5b28', 'nic..."
95421,630f6a41610aed3b69870d01,2022-08-31T23:19:05,50,"[{'accessId': '2f68e30a2629817e7132579c', 'nic..."

In [96]:
r3.to_csv("api_sample2.csv",index = False)

In [ ]:
print(i)

In [97]:
# 자르고 계속
match_urls3 = match_urls2.loc[I+1000:]
match_urls3

                                                         0
95422    https://api.nexon.co.kr/fifaonline4/v1.0/match...
95423    https://api.nexon.co.kr/fifaonline4/v1.0/match...
95424    https://api.nexon.co.kr/fifaonline4/v1.0/match...
95425    https://api.nexon.co.kr/fifaonline4/v1.0/match...
95426    https://api.nexon.co.kr/fifaonline4/v1.0/match...
...                                                    ...
3398371  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398372  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398373  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398374  https://api.nexon.co.kr/fifaonline4/v1.0/match...
3398375  https://api.nexon.co.kr/fifaonline4/v1.0/match...

[3302954 rows x 1 columns]

In [130]:
api = pd.read_csv("api_sample2.csv")
api

,matchId,matchDate,matchType,matchInfo
0,630f902bdaa4ab457d80d526,2022-09-01T02:01:54,50,"[{'accessId': '38f89da916b3455445b303e9', 'nic..."
1,630f8ffee3bc6523b853c125,2022-09-01T02:00:13,50,"[{'accessId': '8ddd8a2e773ba58810d85038', 'nic..."
2,630f8fe2ce134c543bb65992,2022-09-01T02:00:46,50,"[{'accessId': '1f125750eae226adf9ab3878', 'nic..."
3,630f8f6d7199900902a1d249,2022-09-01T02:01:00,50,"[{'accessId': 'cb542e3f735dfd3e5b9f3039', 'nic..."
4,630f851d00e8d130df4a7272,2022-09-01T00:59:31,50,"[{'accessId': 'f8f75e9fc25f7c2914f71115', 'nic..."
...,...,...,...,...
95417,630f6a41b464844a526ce6f6,2022-08-31T23:12:09,50,"[{'accessId': '8f5729ad8930a47b587ea4d2', 'nic..."
95418,630f6a41ae6dd7562cb5905a,2022-08-31T23:15:40,50,"[{'accessId': '3bcf8fb0dcb4b512f3e25756', 'nic..."
95419,630f6a41a0a6ec825a0101a3,2022-08-31T23:14:49,50,"[{'accessId': '36fe21c2f34cd7d73609ff88', 'nic..."
95420,630f6a4171d70963291886a0,2022-08-31T23:13:46,50,"[{'accessId': '19ab9de1bd4bd474574e5b28', 'nic..."
95421,630f6a41610aed3b69870d01,2022-08-31T23:19:05,50,"[{'accessId': '2f68e30a2629817e7132579c', 'nic..."

In [138]:
api.loc[60000:]

,matchId,matchDate,matchType,matchInfo
60000,630f75bcc841fe88d3e4545a,2022-09-01T00:02:31,50,"[{'accessId': '54588176cd5487d16b44d27e', 'nic..."
60001,630f75bcb89d0194af1203a3,2022-09-01T00:03:53,50,"[{'accessId': '044269b45cc5fccff7536ac5', 'nic..."
60002,630f75bca2f07a4dd4f9a7cc,2022-09-01T00:05:26,50,"[{'accessId': '92245aa01b916506633c39c8', 'nic..."
60003,630f75bc9c51fd02d71476bf,2022-09-01T00:03:08,50,"[{'accessId': '2f0fc11f49a210f26edc2059', 'nic..."
60004,630f75bc9611f941d18b6e06,2022-09-01T00:04:12,50,"[{'accessId': '0ff6677c8da1a8800cb28c16', 'nic..."
...,...,...,...,...
95417,630f6a41b464844a526ce6f6,2022-08-31T23:12:09,50,"[{'accessId': '8f5729ad8930a47b587ea4d2', 'nic..."
95418,630f6a41ae6dd7562cb5905a,2022-08-31T23:15:40,50,"[{'accessId': '3bcf8fb0dcb4b512f3e25756', 'nic..."
95419,630f6a41a0a6ec825a0101a3,2022-08-31T23:14:49,50,"[{'accessId': '36fe21c2f34cd7d73609ff88', 'nic..."
95420,630f6a4171d70963291886a0,2022-08-31T23:13:46,50,"[{'accessId': '19ab9de1bd4bd474574e5b28', 'nic..."
95421,630f6a41610aed3b69870d01,2022-08-31T23:19:05,50,"[{'accessId': '2f68e30a2629817e7132579c', 'nic..."

In [ ]:
8/31 밤 11시 ~ 9월 1일 오전 2시